"""Rule-based classifier for the 907 unlabeled messages.

Reads unlabeled_messages.json, produces classification.json.
Rules use sender + subject + snippet to choose 1-3 labels from the 126 available.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


def classify(msg: dict) -> list[str]:
    sender = msg.get("from", "").lower()
    subject = msg.get("subject", "").lower()
    snippet = msg.get("snippet", "").lower()
    text = f"{sender} || {subject} || {snippet}"

    def has(s: str) -> bool:
        return s.lower() in text

    def from_has(s: str) -> bool:
        return s.lower() in sender

    def subj_has(s: str) -> bool:
        return s.lower() in subject

    def snip_has(s: str) -> bool:
        return s.lower() in snippet

    # ============================================================
    # 1. User's own auto-generated unsubscribe emails
    # ============================================================
    if from_has("warrenn@busyweb.co.za"):
        if (
            subj_has("unsubscribe") or subj_has("unsub")
            or "automatically generated by gmail" in snippet
            or "this message was automatically generated" in snippet
            or re.match(r"^[a-zA-Z0-9._-]{6,}$", msg.get("subject", "").strip())  # hash-like
            or "unsub-" in subject or "unsub:" in subject
            or re.match(r"^\d{6,}\.", msg.get("subject", "").strip())  # numbered hash
        ):
            return ["Busyweb", "_Outbox"]
        # User's own Adobe Acrobat shared docs
        if "adobe acrobat" in sender or "echosign" in sender:
            return ["Busyweb", "Notifications"]
        # User from old ABSA work account
        if "absa.africa" in sender:
            return ["Work", "ABSA"]
        return ["Busyweb"]

    # User from old ABSA work email or work colleagues at ABSA
    if from_has("absa.africa") and not from_has("cardnotification") and not from_has("officialemail"):
        return ["Work", "ABSA"]

    # ============================================================
    # 2. ABSA bank transactional notifications
    # ============================================================
    if from_has("absa.co.za") or from_has("absacapital") or "officialemail@absa" in sender or "cardnotification@absa" in sender:
        if "credit card statement" in subject or "statement" in subject:
            return ["ABSA", "Finance"]
        return ["ABSA", "Notifications"]

    # ============================================================
    # 3. Banks and Finance
    # ============================================================
    if from_has("fnbstatements") or from_has("@fnb.co.za") or "fnbcardemail" in sender or "fnbcheque" in sender:
        return ["FNB", "Finance"]
    if from_has("rmbprivatebank") or from_has("rmb.co.za"):
        return ["Finance", "Notifications"]
    if from_has("stripe.com"):
        return ["Stripe", "Finance"]
    if from_has("wise.com"):
        return ["Wise", "Finance"]
    if from_has("wirexapp"):
        return ["Wise", "Finance"]
    if from_has("discovery.co.za"):
        return ["Discovery", "Finance"]
    if from_has("@xm.com") or from_has("xmglobal"):
        return ["Finance", "Notifications"]
    if from_has("etradefinancial") or from_has("e*trade") or from_has("etrade@"):
        return ["Finance", "Notifications"]
    if from_has("clientam.com") or from_has("zackstrade") or from_has("zacks trade"):
        return ["Zacks", "Finance", "Notifications"]
    if from_has("interactivebrokers") or "interactive brokers" in sender:
        return ["Finance", "Notifications"]
    if from_has("payoneer"):
        return ["Payoneer", "Notifications"]
    if from_has("grey.co") or "from grey" in sender:
        return ["Finance", "Notifications"]
    if from_has("polygon.io"):
        return ["Newsletters", "Finance"]
    if from_has("lightstreetinvestments") or from_has("lightstreet"):
        return ["Work", "Finance"]
    if from_has("foundationcapital"):
        return ["Work", "Finance"]
    if from_has("liblink.co.za") or "noluthando" in sender:
        return ["Liberty", "Finance"]
    if from_has("@liberty") or from_has("liberty.co.za"):
        return ["Liberty", "Finance"]

    # ============================================================
    # 4. Crypto exchanges
    # ============================================================
    if from_has("coinbase"):
        return ["Coinbase", "Notifications"]
    if from_has("binance"):
        return ["Binance", "Notifications"]
    if from_has("coinex"):
        return ["Coinex", "Notifications"]
    if from_has("@bybit"):
        return ["Bybit", "Notifications"]
    if from_has("cex.io"):
        return ["Cex", "Notifications"]
    if from_has("luno.com"):
        return ["Luno", "Notifications"]
    if from_has("kraken.com"):
        return ["Newsletters", "Notifications"]
    if from_has("trezor"):
        return ["Trezor", "Notifications"]
    if from_has("yieldnodes"):
        return ["Finance", "Notifications"]
    if from_has("cryptohopper"):
        return ["Newsletters", "Notifications"]
    if from_has("coinglass"):
        return ["Notifications"]
    if from_has("dappradar") or from_has("hotcoin"):
        return ["Newsletters", "Notifications"]
    if from_has("crypto.com"):
        return ["Notifications"]
    if from_has("lunarcrush"):
        return ["Notifications"]
    if from_has("airtm"):
        return ["Notifications"]

    # ============================================================
    # 5. Travel and bookings
    # ============================================================
    if from_has("travelstart"):
        return ["Travel", "Newsletters"]
    if from_has("booking.com") or "bookings.millerandcarter" in sender:
        return ["Booking", "Travel"]
    if from_has("singaporeair") or from_has("singapore airlines"):
        return ["Travel", "Notifications"]
    if from_has("agoda"):
        return ["Booking", "Travel"]
    if from_has("traveldomain"):
        return ["Travel"]
    if from_has("hepstar.com"):
        return ["Travel", "Receipts"]
    if from_has("thenaturaladventure") or "nakasendo" in text:
        return ["Travel", "Nakasendo Trail"]
    if from_has("nextcarehealth") or "travel insurance" in text:
        return ["Travel", "Bills"]
    if from_has("capenature"):
        return ["Travel", "Notifications"]
    if from_has("flightinfo"):
        return ["Travel", "Notifications"]
    if from_has("jsdbiz"):
        return ["Travel", "Bills"]

    # ============================================================
    # 6. AWS / Amazon
    # ============================================================
    if from_has("@iq.aws") or "aws iq" in subject:
        return ["AWSIQ", "Work"]
    if from_has("amazonaws") or from_has("@aws.com") or from_has("@aws.amazon") or from_has("awsapps.com") or "aws notifications" in sender or "aws certification" in sender or "amazon web services" in sender:
        return ["AWS", "Notifications"]

    # ============================================================
    # 7. Insurance and Bills
    # ============================================================
    if from_has("autogen") or "auto & general" in text or "auto&general" in text or from_has("1life.co.za"):
        return ["Bills", "Notifications"]
    if from_has("kingprice"):
        return ["Kingprice", "Bills"]
    if from_has("nextinsurance") or from_has("insureon"):
        return ["Bills", "Notifications"]
    if from_has("@telkom.co.za") or from_has("telkomsa") or from_has("@telkom"):
        return ["Telkom", "Bills"]
    if from_has("vodacom"):
        return ["Vodacom", "Bills"]
    if from_has("webafrica"):
        return ["Bills", "Notifications"]
    if from_has("unitedworldtelecom"):
        return ["Bills", "Notifications"]
    if from_has("@octotel") or "octotel" in sender:
        return ["Bills"]
    if from_has("velocitypayment") or from_has("delaware.gov") or "delaware one stop" in sender or "delawarefile" in sender:
        return ["Delaware", "Bills"]
    if from_has("e-government") or from_has("e-governmnt") or from_has("info@e-delaware"):
        return ["Delaware", "Bills"]
    if from_has("payCity") or from_has("paycity"):
        return ["Bills", "Notifications"]
    if from_has("sars.gov.za") or from_has("its-sars") or from_has("efile.com") or from_has("efilemail") or "turbotax" in sender or "tax return" in subject or "tax filing" in subject or "irs" in sender:
        return ["Bills", "Notifications"]
    if from_has("track1099"):
        return ["Bills", "Notifications"]
    if from_has("ampath.co.za") or from_has("pathcare") or from_has("mediclinic") or from_has("blaineassoc") or from_has("dentaldongray") or from_has("sedgedentist") or from_has("drgawie") or from_has("eidmedic") or from_has("nextec.co.za"):
        return ["Bills", "Notifications"]
    if from_has("dr-jon-morley") or from_has("thehealthpharm"):
        return ["Bills"]
    if from_has("knysnawaterproofing") or from_has("pracpay"):
        return ["Bills"]
    if from_has("custombarz"):
        return ["Bills"]
    if from_has("computermania"):
        return ["Receipts", "Bills"]
    if from_has("paygate"):
        return ["Bills", "Notifications"]
    if from_has("payfast"):
        return ["Bills", "Notifications"]
    if from_has("cipc.co.za"):
        return ["Bills", "Notifications"]
    if from_has("registry.net.za") or "ticketman@co.za" in sender or from_has("domainnameverification"):
        return ["Bills", "Notifications"]
    if from_has("wave") and ("waveapps" in sender or "wave " in sender):
        return ["Wave", "Bills"]
    if from_has("rsync.net"):
        return ["Bills", "Notifications"]
    if from_has("anthropic"):
        return ["Anthropic", "Notifications"]
    if from_has("netflix"):
        return ["Netflix", "Receipts"] if "Netflix" in {"Netflix"} else ["Receipts", "Notifications"]
    if from_has("paddle.com") or "paddle.com" in subject:
        return ["paddle", "Receipts"]
    if from_has("brilliant.org"):
        return ["Brilliant", "Bills"]
    if from_has("@cipc"):
        return ["Bills"]
    if from_has("pargo.co.za") or "dis-chem" in text or "dischem" in text:
        return ["Dischem", "Notifications"]
    if from_has("@aramex") or from_has("fastway"):
        return ["Notifications"]
    if from_has("blueblockerlens") or from_has("eareview.net"):
        return ["Bills", "Notifications"]
    if "annual policy" in subject or "policy number" in subject or "policy schedule" in subject:
        return ["Bills"]
    if "your statement" in subject or "monthly statement" in subject or "daily activity statement" in subject:
        return ["Finance", "Notifications"]

    # ============================================================
    # 8. iStore / Apple
    # ============================================================
    if from_has("istore.co.za") or from_has("@istore"):
        return ["iStore", "Receipts"]
    if from_has("apple.com") or from_has("nvidia") or "tp-link" in sender or "asus" in sender:
        return ["Notifications"]
    if "icare" in sender and "warranty" in subject.lower():
        return ["Apple", "Notifications"]

    # ============================================================
    # 9. Newsletters/promotional
    # ============================================================
    if from_has("ideabrowser"):
        return ["ideabrowser", "Newsletters"]
    if from_has("medium.com"):
        return ["medium", "Newsletters"]
    if from_has("substack"):
        return ["Newsletters"]
    if from_has("seekingalpha"):
        return ["Newsletters"]
    if from_has("flippa"):
        return ["Newsletters"]
    if from_has("coursera"):
        return ["Newsletters"]
    if from_has("japanesepod101"):
        return ["Newsletters"]
    if from_has("mexc"):
        return ["Mexc", "Newsletters"]
    if from_has("okx.com"):
        return ["Okx", "Newsletters"]
    if from_has("gate.io") or from_has("gate.com"):
        return ["Newsletters"]
    if from_has("plus500"):
        return ["Newsletters"]
    if from_has("stackshare"):
        return ["Newsletters"]
    if from_has("tutorialsdojo"):
        return ["Newsletters"]
    if from_has("evernote"):
        return ["Evernote", "Newsletters"]
    if from_has("livescribe"):
        return ["Newsletters"]
    if from_has("quora"):
        return ["Quora", "Newsletters"]
    if from_has("wordpress"):
        return ["Newsletters"]
    if from_has("meetup"):
        return ["Newsletters"]
    if from_has("offerzen"):
        return ["Offerzen", "Newsletters"]
    if from_has("bitget"):
        return ["Newsletters", "Notifications"]
    if from_has("etoro"):
        return ["Newsletters"]
    if from_has("juliangoldie") or from_has("justinwelsh"):
        return ["Newsletters"]
    if from_has("linuxacademy"):
        return ["Linuxacademy", "Newsletters"]
    if from_has("lumosity"):
        return ["Newsletters"]
    if from_has("jobleads"):
        return ["Newsletters"]
    if from_has("maxmahershow"):
        return ["Newsletters"]
    if from_has("openai"):
        return ["Openai", "Newsletters"]
    if from_has("scrimba"):
        return ["Newsletters"]
    if from_has("wallmine"):
        return ["Newsletters", "Finance"]
    if from_has("pnet.co.za") or from_has("@pnet"):
        return ["Pnet", "Newsletters"]
    if from_has("tradingview"):
        return ["Newsletters"]
    if from_has("xt.com"):
        return ["Newsletters", "Notifications"]
    if from_has("ein-itin"):
        return ["Newsletters", "Bills"]
    if from_has("patreon"):
        return ["Patreon", "Newsletters"]
    if from_has("cal.com"):
        return ["Newsletters"]
    if from_has("discoursemail"):
        return ["Newsletters"]
    if from_has("replit"):
        return ["Newsletters"]
    if from_has("ngrok"):
        return ["Newsletters"]
    if from_has("stoic.ai"):
        return ["Newsletters"]
    if from_has("microsoft") and ("e-mails.microsoft" in sender or "e-mail.microsoft" in sender or "microsoft tech news" in sender or "communication.microsoft" in sender):
        return ["Newsletters"]
    if from_has("@microsoft.com"):
        return ["Notifications"]
    if from_has("preply"):
        return ["Newsletters"]
    if from_has("databento"):
        return ["Notifications"]
    if from_has("cursor.com"):
        return ["Newsletters"]
    if from_has("wakatime"):
        return ["Newsletters"]
    if from_has("blinkist"):
        return ["Newsletters"]
    if from_has("profitshouse") or from_has("today.libertystockn") or from_has("ontheluckywave") or from_has("todayinthemarkets") or from_has("auratech.info") or "doctor warning" in sender or from_has("cageask"):
        return ["Junk E-mail"]
    if from_has("statista"):
        return ["Newsletters"]
    if from_has("@miro.com") or from_has("billing.miro"):
        return ["Bills", "Notifications"]
    if from_has("logrocket"):
        return ["Newsletters"]
    if from_has("beehiiv"):
        return ["Newsletters"]
    if from_has("the-ai-report"):
        return ["Newsletters"]
    if from_has("fullstack") or from_has("newline"):
        return ["Newsletters"]
    if from_has("crunchlabs"):
        return ["crunchlabs", "Newsletters"]
    if from_has("dndbeyond"):
        return ["dndbeyond", "Newsletters"]
    if from_has("kurzgesagt") or from_has("kurtzgesaght"):
        return ["kurtzgesaght", "Receipts"]
    if from_has("nebula"):
        return ["nebula", "Newsletters"]
    if from_has("skillshare") or from_has("headspace") or from_has("soundcloud") or from_has("disqus") or from_has("@enki.com"):
        return ["Newsletters", "Notifications"]
    if from_has("stackoverflow"):
        return ["Newsletters"]
    if from_has("@scribd") or from_has("scribd.com"):
        return ["scribd", "Newsletters"]
    if from_has("substack"):
        return ["Newsletters"]
    if from_has("grammarly"):
        return ["Grammarly", "Newsletters"]
    if from_has("plextouch") or from_has("nytimes") or from_has("economist") or from_has("ft.com") or from_has("wsj.com"):
        return ["Newsletters"]
    if from_has("epicgames") or "epic games" in sender:
        return ["epic games", "Notifications"]
    if from_has("playstation") or from_has("sonyentertainment"):
        return ["sony", "Notifications"]
    if from_has("sony"):
        return ["sony", "Newsletters"]
    if from_has("netflorist"):
        return ["Newsletters"]
    if from_has("netflix"):
        return ["Receipts", "Notifications"]
    if from_has("teamviewer"):
        return ["Notifications"]
    if from_has("global call forwarding") or from_has("unitedworldtelecom") or "uwt" in sender:
        return ["Newsletters", "Bills"]

    # ============================================================
    # 10. Authentication / verification / login codes
    # ============================================================
    if from_has("no-reply@verificationemail") or "verification code" in subject or "your code" in subject:
        return ["Notifications"]
    if from_has("@google.com") or from_has("noreply@google"):
        return ["Google", "Notifications"]
    if from_has("gmail.com") and "delivery status notification" in subject:
        return ["Notifications"]
    if from_has("mailer-daemon"):
        return ["Notifications"]
    if from_has("docusign"):
        return ["Docusign", "Notifications"]
    if from_has("taxdome"):
        return ["Bills", "Notifications"]
    if from_has("@atlassian") or from_has("@id.atlassian"):
        return ["Notifications", "Work"]
    if from_has("bitbucket"):
        return ["Github", "Work"]
    if from_has("github"):
        return ["Github", "Work"]
    if from_has("trello"):
        return ["Trello", "Work"]
    if from_has("notion"):
        return ["Notion", "Work"]
    if from_has("slack.com"):
        return ["Slack", "Notifications"]
    if from_has("ipinfo") or from_has("@ipinfo"):
        return ["Notifications"]
    if from_has("nvidia"):
        return ["Notifications"]
    if from_has("tp-link"):
        return ["Notifications"]
    if from_has("loom"):
        return ["Loom", "Notifications"]
    if from_has("playtomic"):
        return ["Newsletters", "Notifications"]
    if from_has("symless") or "synergy" in subject:
        return ["Notifications"]
    if from_has("readme.io"):
        return ["Notifications"]
    if from_has("webflow"):
        return ["Notifications", "Newsletters"]
    if from_has("expo.io"):
        return ["Notifications"]
    if from_has("typeform"):
        return ["Notifications"]
    if from_has("zoom.us") or from_has("@zoom.us"):
        return ["Notifications", "Work"]
    if from_has("ikmnet"):
        return ["Notifications", "Work"]
    if from_has("scrumalliance"):
        return ["Notifications", "Work"]
    if from_has("badging@scrumalliance"):
        return ["Notifications", "Work"]
    if from_has("nightsbridge"):
        return ["Travel", "Notifications"]
    if from_has("supportvtsn") or "veterans trauma" in sender:
        return ["Junk E-mail"]
    if from_has("sanparks"):
        return ["Travel", "Notifications"]
    if from_has("lookout.com"):
        return ["Notifications"]
    if from_has("ftxnoticing") or from_has("noticing.ra.kroll"):
        return ["Finance", "Notifications"]
    if from_has("@dochub") or from_has("@hellosign") or from_has("track1099"):
        return ["Notifications"]
    if from_has("scrumalliance") or from_has("hellosign"):
        return ["Notifications"]
    if from_has("@adblock"):
        return ["adblock", "Notifications"]
    if from_has("blur-support") or from_has("getabine"):
        return ["Notifications"]
    if from_has("itch.io"):
        return ["Receipts", "Notifications"]

    # ============================================================
    # 11. Recruitment / Work
    # ============================================================
    recruiters = [
        "e-merge.co.za", "sabenzait.co.za", "miprint.co.za", "pillango.co.za",
        "esmartgroup.co.za", "networkrecruitment.co.za", "stand-outstaffing.co.za",
        "stand-out staffing", "ringier.co.za", "skillzpage.com", "jobcrystal.com",
        "ilaunch.co.za", "1-grid.breezy-mail", "bberecruitment.co.za", "pbtgroup.co.za",
        "believeresourcing.com", "millenniumtech.co.za", "kmgt.co.za", "the-argo.net",
        "scoutit.online", "aridconsulting.co.za", "tcbusiness.com", "plusonex.com",
        "knysnatoyota.co.za", "attainpeople.co.za", "ikbi.co.za", "holbourne.co.za",
        "peoplesolved.com", "swiftmomentum.com", "goldenrule.co.za", "planet10.recruitmail",
        "mspstaffing.co.za", "resourgenix.com", "perfsys.com", "lesedipfs.co.za",
        "bamboohr.com", "remoteok.com", "topcv.com", "remote.com", "intch.org",
        "jobs-listings@linkedin", "credit gateway", "tigo.com.ni", "hirefrederick",
    ]
    if any(r in sender for r in recruiters) or "remote role" in subject or "career opportunit" in subject:
        return ["Pnet", "Newsletters"]
    if from_has("linkedin.com"):
        return ["Newsletters"]
    if from_has("@linkedin"):
        return ["Newsletters"]
    if "@" in sender and any(d in sender for d in ["sidisglobal", "lifelinesneuro", "bridgewaybentech", "pathosethos", "agio.com", "wyrick.com", "duke.edu", "jasonwright.org", "ioco.tech", "vpmteams.co.za", "vpmteam.co.za", "senterprisys", "lightstreetinvestments", "softwerk.se", "emsbilling.com", "wakanda", "vivianchen@hitrust", "lekentle@mohlala", "byron.guernsey", "matt.becker", "matt arbesfeld"]):
        return ["Work"]
    if from_has("eoh.com"):
        return ["Work"]
    if from_has("titancharts") or from_has("hitrust"):
        return ["Work"]
    if from_has("relevant.us"):
        return ["Relevant", "Work"]
    if from_has("veritybiosciences"):
        return ["Verity", "Work"]
    if from_has("backslash.co.za"):
        return ["Work"]
    if from_has("realID phase") or from_has("nanofibre.co.za"):
        return ["Work"]
    if from_has("simola"):
        return ["Simola", "Personal"]
    if from_has("simolahoa") or from_has("@simola"):
        return ["Simola", "Personal"]
    if from_has("vpmteam") or from_has("buffel") or "buffelspoort" in subject:
        return ["Buffel", "Bills"]

    # ============================================================
    # 12. Seeff Properties / Personal real estate
    # ============================================================
    if from_has("seeff") or from_has("payprop.com") or from_has("@payprop"):
        return ["Seef", "Bills"]

    # ============================================================
    # 13. Adobe Acrobat / Doc signing
    # ============================================================
    if from_has("echosign") or from_has("hellosign") or from_has("@mail.hellosign"):
        return ["Notifications", "Work"]
    if from_has("adobe.com") or "via adobe acrobat" in sender:
        return ["Notifications"]
    if from_has("scrumalliance"):
        return ["Notifications", "Work"]

    # ============================================================
    # 14. Junk / Spam / Adult / Scams
    # ============================================================
    junk_indicators = [
        "lhspla.net", "elogica.com.br", "kobe-u.ne.jp/processing", "thepunjabschool",
        "institutxxvolimpiada", "serpot-hostel", "groupe-nsk", "tigo.com.ni",
        "chengguokeji", "sfr.fr/femme africaine", "femme-africaine", "hungariansfx",
        "vxnbill", "vxsbill", "onlyfans", "sexart.com", "famesupport", "adultprime",
        "vixen.com", "geek squad", "norton™ internet security expired",
        "memory loss and alzheimer", "harvard-backed memory", "doctor warning",
        "is your bank on the list", "trump just signed", "maha docs final warning",
        "this is gabriella", "your personal representative",
        "iciod has been locked", "iCloud id has been locked",
        "global visa agency", "your verification code 49463",
    ]
    if any(ind.lower() in text for ind in junk_indicators):
        return ["Junk E-mail"]
    if from_has("kobe-u.ne.jp"):
        return ["Junk E-mail"]
    if from_has("itin") and "tax" not in subject:
        return ["Junk E-mail"]

    # ============================================================
    # 15. Personal contacts and family/friends
    # ============================================================
    if "tamarin_sage@me.com" in sender:
        return ["Personal"]
    if from_has("hotmail.com"):
        return ["Hotmail", "Personal"]
    if from_has("yahoo.com"):
        return ["Yahoo", "Personal"]
    if from_has("icloud.com"):
        return ["iCloud", "Personal"]
    if from_has("@gmail.com"):
        return ["Gmail", "Personal"]
    if from_has("dannato17@outlook"):
        return ["Hotmail", "Personal"]

    # ============================================================
    # 16. Generic fallbacks
    # ============================================================
    # Tracking / delivery
    if subj_has("tracking notification") or subj_has("shipment") or subj_has("parcel") or subj_has("delivery"):
        return ["Notifications"]

    # Account / verification / login
    if subj_has("verification code") or subj_has("verify your email") or subj_has("confirm your email") or subj_has("sign in") or subj_has("login") or subj_has("authentication") or subj_has("welcome to") or subj_has("account confirmation") or subj_has("changes to your"):
        return ["Notifications"]

    # Payments / invoices / receipts
    if subj_has("payment") or subj_has("invoice") or subj_has("receipt") or subj_has("order") or subj_has("statement"):
        return ["Receipts", "Bills"]

    # Interview/job-related
    if subj_has("interview") or subj_has("opportunity") or subj_has("position") or subj_has("application"):
        return ["Pnet", "Work"]

    # Welcome / promo / inactive account / product updates / hello
    if subj_has("inactive") or subj_has("updates") or subj_has("welcome") or subj_has("exciting") or "thanks for" in subject or "we're glad" in subject or subj_has("review"):
        return ["Newsletters"]

    # Estimate / quote → Bills
    if subj_has("estimate") or subj_has("quote"):
        return ["Bills"]

    # Last-resort: assume any remaining promo-looking email is Newsletters,
    # else Notifications
    if "noreply" in sender or "no-reply" in sender or "donotreply" in sender:
        return ["Notifications"]
    return ["Newsletters"]


def main():
    src = Path("unlabeled_messages.json")
    dst = Path("classification.json")
    data = json.loads(src.read_text())
    messages = data["messages"]
    available = set(data["available_labels"])
    # Add Other as it's in the existing tree but not technically in available_labels output
    # Actually it IS in available_labels — let's not worry about it.

    classification: dict[str, list[str]] = {}
    label_counts: dict[str, int] = {}
    unmapped = 0

    for msg in messages:
        labels = classify(msg)
        # Filter to only available labels (case-insensitive)
        available_cf = {a.casefold(): a for a in available}
        filtered: list[str] = []
        for lbl in labels:
            canonical = available_cf.get(lbl.casefold())
            if canonical:
                filtered.append(canonical)
        if not filtered:
            filtered = ["Other"] if "Other" in available else []
            unmapped += 1
        if filtered:
            classification[msg["id"]] = filtered
            for l in filtered:
                label_counts[l] = label_counts.get(l, 0) + 1

    dst.write_text(json.dumps(classification, indent=2))
    print(f"classified {len(classification)} messages; {unmapped} fell through to Other", file=sys.stderr)
    print(f"per-label counts:", file=sys.stderr)
    for name in sorted(label_counts, key=lambda n: -label_counts[n]):
        print(f"  {label_counts[name]:5d}  {name}", file=sys.stderr)


if __name__ == "__main__":
    main()
