from __future__ import annotations

import pytest

from gmail_cleanup import rule_interpreter as ri


def _thread(**overrides) -> dict:
    base = {"from": "", "subject": "", "snippet": ""}
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# Operator tests
# ---------------------------------------------------------------------------


def test_from_contains_matches_substring_case_insensitive():
    assert ri.evaluate_match({"from_contains": "stripe.com"}, _thread(**{"from": "support@STRIPE.COM"}))


def test_from_contains_no_match():
    assert not ri.evaluate_match({"from_contains": "stripe.com"}, _thread(**{"from": "support@example.com"}))


def test_from_contains_any_matches_at_least_one():
    m = {"from_contains_any": ["telkomsa.net", "telkom.co.za"]}
    assert ri.evaluate_match(m, _thread(**{"from": "bills@telkom.co.za"}))
    assert ri.evaluate_match(m, _thread(**{"from": "noreply@telkomsa.net"}))
    assert not ri.evaluate_match(m, _thread(**{"from": "noreply@vodacom.co.za"}))


def test_from_contains_any_empty_list_never_matches():
    assert not ri.evaluate_match({"from_contains_any": []}, _thread(**{"from": "foo@bar.com"}))


def test_from_not_contains_any_negation():
    m = {"from_not_contains_any": ["cardnotification", "officialemail"]}
    assert ri.evaluate_match(m, _thread(**{"from": "john@absa.africa"}))
    assert not ri.evaluate_match(m, _thread(**{"from": "cardnotification@absa.africa"}))
    assert not ri.evaluate_match(m, _thread(**{"from": "officialemail@absa.co.za"}))


def test_from_not_contains_any_empty_list_always_true():
    assert ri.evaluate_match({"from_not_contains_any": []}, _thread(**{"from": "foo@bar.com"}))


def test_subject_contains_matches():
    assert ri.evaluate_match({"subject_contains": "receipt"}, _thread(subject="Your Receipt"))


def test_subject_contains_any_matches():
    m = {"subject_contains_any": ["receipt", "invoice", "order"]}
    assert ri.evaluate_match(m, _thread(subject="Your order #123"))
    assert not ri.evaluate_match(m, _thread(subject="Hello there"))


def test_subject_not_contains_any_negation():
    m = {"subject_not_contains_any": ["unsubscribe"]}
    assert ri.evaluate_match(m, _thread(subject="Newsletter"))
    assert not ri.evaluate_match(m, _thread(subject="To unsubscribe click here"))


def test_subject_starts_with_any_strips_whitespace():
    m = {"subject_starts_with_any": ["otp", "code"]}
    assert ri.evaluate_match(m, _thread(subject="  OTP: 482911"))
    assert ri.evaluate_match(m, _thread(subject="code 12345"))
    assert not ri.evaluate_match(m, _thread(subject="your code is 12345"))  # not at start


def test_subject_matches_regex():
    # hash-like subject pattern (numeric + dot prefix)
    m = {"subject_matches_regex": r"^\d{6,}\."}
    assert ri.evaluate_match(m, _thread(subject="123456.abc"))
    assert not ri.evaluate_match(m, _thread(subject="hello world"))


def test_snippet_contains():
    assert ri.evaluate_match({"snippet_contains": "automatically generated"}, _thread(snippet="this email is automatically generated by gmail"))
    assert not ri.evaluate_match({"snippet_contains": "automatically generated"}, _thread(snippet="manual email"))


def test_snippet_contains_any():
    m = {"snippet_contains_any": ["foo", "bar"]}
    assert ri.evaluate_match(m, _thread(snippet="has bar in it"))
    assert not ri.evaluate_match(m, _thread(snippet="has baz in it"))


def test_text_contains_any_searches_from_subject_snippet_combined():
    m = {"text_contains_any": ["onlyfans"]}
    assert ri.evaluate_match(m, _thread(**{"from": "onlyfans@somewhere.com"}))
    assert ri.evaluate_match(m, _thread(subject="onlyfans content"))
    assert ri.evaluate_match(m, _thread(snippet="check out onlyfans"))
    assert not ri.evaluate_match(m, _thread(subject="ordinary subject"))


def test_any_of_at_least_one_match():
    m = {"any_of": [{"from_contains": "stripe"}, {"subject_contains": "payout"}]}
    assert ri.evaluate_match(m, _thread(**{"from": "support@stripe.com"}))
    assert ri.evaluate_match(m, _thread(subject="Your payout"))
    assert not ri.evaluate_match(m, _thread(**{"from": "user@example.com", "subject": "Hello"}))


def test_all_of_all_must_match():
    m = {"all_of": [{"from_contains": "stripe"}, {"subject_contains": "payout"}]}
    assert ri.evaluate_match(m, _thread(**{"from": "support@stripe.com", "subject": "Your payout"}))
    assert not ri.evaluate_match(m, _thread(**{"from": "support@stripe.com", "subject": "Hello"}))


def test_top_level_keys_are_anded():
    m = {"from_contains": "absa.africa", "from_not_contains_any": ["cardnotification"]}
    assert ri.evaluate_match(m, _thread(**{"from": "john@absa.africa"}))
    assert not ri.evaluate_match(m, _thread(**{"from": "cardnotification@absa.africa"}))


# ---------------------------------------------------------------------------
# Resolution algorithm
# ---------------------------------------------------------------------------


def _spec(**overrides) -> dict:
    base = {
        "version": 1,
        "sender_rules": [],
        "additive_subject_rules": [],
        "fallback_rules": [],
    }
    base.update(overrides)
    return base


def test_phase1_first_match_wins():
    spec = _spec(sender_rules=[
        {"id": "stripe", "match": {"from_contains": "stripe.com"}, "labels": ["finance", "stripe"]},
        {"id": "fnb", "match": {"from_contains": "fnb.co.za"}, "labels": ["finance", "fnb"]},
    ])
    assert ri.classify(_thread(**{"from": "x@stripe.com"}), spec) == ["finance", "stripe"]


def test_phase1_no_match_falls_through_to_phase3():
    spec = _spec(
        sender_rules=[{"id": "stripe", "match": {"from_contains": "stripe.com"}, "labels": ["finance", "stripe"]}],
        fallback_rules=[{"id": "default", "labels": ["newsletters"]}],
    )
    assert ri.classify(_thread(**{"from": "x@nowhere.com"}), spec) == ["newsletters"]


def test_phase2_layers_on_phase1():
    spec = _spec(
        sender_rules=[{"id": "stripe", "match": {"from_contains": "stripe.com"}, "labels": ["finance", "stripe"]}],
        additive_subject_rules=[
            {"id": "receipts", "match": {"subject_contains_any": ["receipt", "invoice"]}, "labels": ["receipts"]},
        ],
    )
    result = ri.classify(_thread(**{"from": "x@stripe.com", "subject": "Your receipt"}), spec)
    assert result == ["finance", "stripe", "receipts"]


def test_phase2_alone_skips_phase3():
    """Phase 3 only fires if neither phase 1 nor phase 2 produced labels."""
    spec = _spec(
        additive_subject_rules=[
            {"id": "receipts", "match": {"subject_contains_any": ["receipt"]}, "labels": ["receipts"]},
        ],
        fallback_rules=[{"id": "default", "labels": ["newsletters"]}],
    )
    result = ri.classify(_thread(**{"from": "x@unknown.com", "subject": "receipt for purchase"}), spec)
    assert result == ["receipts"]


def test_phase3_first_match_wins():
    spec = _spec(fallback_rules=[
        {"id": "junk", "match": {"text_contains_any": ["onlyfans"]}, "labels": ["junk-e-mail"]},
        {"id": "noreply", "match": {"from_contains_any": ["noreply", "no-reply"]}, "labels": ["notifications"]},
        {"id": "default", "labels": ["newsletters"]},
    ])
    assert ri.classify(_thread(**{"from": "x@onlyfans.com"}), spec) == ["junk-e-mail"]
    assert ri.classify(_thread(**{"from": "noreply@example.com"}), spec) == ["notifications"]
    assert ri.classify(_thread(**{"from": "person@example.com"}), spec) == ["newsletters"]


def test_phase3_default_rule_with_no_match_always_matches():
    spec = _spec(fallback_rules=[
        {"id": "default", "labels": ["newsletters"]},
    ])
    assert ri.classify(_thread(**{"from": "x@anywhere.com"}), spec) == ["newsletters"]


def test_phase2_multiple_additive_rules_all_apply():
    spec = _spec(
        sender_rules=[{"id": "stripe", "match": {"from_contains": "stripe.com"}, "labels": ["finance", "stripe"]}],
        additive_subject_rules=[
            {"id": "receipts", "match": {"subject_contains": "receipt"}, "labels": ["receipts"]},
            {"id": "otp", "match": {"subject_contains_any": ["verification code"]}, "labels": ["otp"]},
        ],
    )
    result = ri.classify(_thread(**{"from": "x@stripe.com", "subject": "receipt and verification code"}), spec)
    assert result == ["finance", "stripe", "receipts", "otp"]


def test_no_match_anywhere_returns_empty():
    spec = _spec()
    assert ri.classify(_thread(**{"from": "x@unknown.com"}), spec) == []


def test_labels_deduplicate_preserving_first_seen_order():
    spec = _spec(
        sender_rules=[{"id": "a", "match": {"from_contains": "stripe"}, "labels": ["finance", "stripe"]}],
        additive_subject_rules=[
            # The "stripe" label appears in both phase 1 and phase 2 — should only appear once.
            {"id": "b", "match": {"subject_contains": "payout"}, "labels": ["stripe", "receipts"]},
        ],
    )
    result = ri.classify(_thread(**{"from": "x@stripe.com", "subject": "Your payout"}), spec)
    assert result == ["finance", "stripe", "receipts"]


def test_complex_real_world_absa_work_pattern():
    """ABSA work colleagues vs ABSA bank — must distinguish."""
    spec = _spec(sender_rules=[
        {
            "id": "absa-work",
            "match": {
                "from_contains": "absa.africa",
                "from_not_contains_any": ["cardnotification", "officialemail"],
            },
            "labels": ["work", "absa"],
        },
        {
            "id": "absa-bank-statement",
            "match": {
                "from_contains_any": ["absa.co.za", "absacapital", "officialemail@absa", "cardnotification@absa"],
                "subject_contains_any": ["statement", "credit card statement"],
            },
            "labels": ["absa", "finance"],
        },
        {
            "id": "absa-bank-other",
            "match": {"from_contains_any": ["absa.co.za", "absacapital", "officialemail@absa", "cardnotification@absa"]},
            "labels": ["absa", "notifications"],
        },
    ])
    assert ri.classify(_thread(**{"from": "colleague@absa.africa"}), spec) == ["work", "absa"]
    assert ri.classify(_thread(**{"from": "cardnotification@absa.africa", "subject": "Statement"}), spec) == ["absa", "finance"]
    assert ri.classify(_thread(**{"from": "noreply@absa.co.za", "subject": "Transaction"}), spec) == ["absa", "notifications"]


# ---------------------------------------------------------------------------
# Loading and validation
# ---------------------------------------------------------------------------


def test_load_rules_from_yaml_string():
    yaml_text = """
version: 1
sender_rules:
  - id: stripe
    match:
      from_contains: stripe.com
    labels: [finance, stripe]
additive_subject_rules: []
fallback_rules:
  - id: default
    labels: [newsletters]
"""
    spec = ri.load_rules_from_string(yaml_text)
    assert spec["version"] == 1
    assert spec["sender_rules"][0]["id"] == "stripe"


def test_load_rules_rejects_unknown_version():
    yaml_text = """
version: 99
sender_rules: []
additive_subject_rules: []
fallback_rules: []
"""
    with pytest.raises(ValueError, match="version"):
        ri.load_rules_from_string(yaml_text)


def test_load_rules_rejects_missing_version():
    yaml_text = """
sender_rules: []
additive_subject_rules: []
fallback_rules: []
"""
    with pytest.raises(ValueError, match="version"):
        ri.load_rules_from_string(yaml_text)


def test_load_rules_rejects_duplicate_rule_ids():
    yaml_text = """
version: 1
sender_rules:
  - id: dup
    match: {from_contains: foo}
    labels: [a]
  - id: dup
    match: {from_contains: bar}
    labels: [b]
additive_subject_rules: []
fallback_rules: []
"""
    with pytest.raises(ValueError, match="duplicate"):
        ri.load_rules_from_string(yaml_text)


def test_load_rules_rejects_sender_rule_with_subject_operator():
    """sender_rules' match is restricted to sender operators only."""
    yaml_text = """
version: 1
sender_rules:
  - id: oops
    match:
      from_contains: stripe.com
      subject_contains: payout
    labels: [a]
additive_subject_rules: []
fallback_rules: []
"""
    with pytest.raises(ValueError, match="sender_rule"):
        ri.load_rules_from_string(yaml_text)


def test_load_rules_rejects_unknown_operator():
    yaml_text = """
version: 1
sender_rules:
  - id: oops
    match:
      from_starts_with_blue: foo
    labels: [a]
additive_subject_rules: []
fallback_rules: []
"""
    with pytest.raises(ValueError, match="unknown operator"):
        ri.load_rules_from_string(yaml_text)
