// DO NOT EDIT — generated from gmail_cleanup/rules.yaml.
// Regenerate with: python -m gmail_cleanup generate-apps-script
//
// RULES — Phase 1 sender-based labelers; each rule's query targets
// `-has:userlabels` threads in organizeInbox().
// SUBJECT_RULES — Phase 2 additive subject overlays.


const RULES = [
  { id: 'telkom', query: 'from:(telkomsa.net OR telkom.co.za)', labels: ['bills', 'telkom'] },
  { id: 'vodacom-sender', query: 'from:vodacom.co.za', labels: ['bills', 'vodacom'] },
  { id: 'kingprice-sender', query: 'from:kingprice.co.za', labels: ['bills', 'kingprice'] },
  { id: 'liberty-sender', query: 'from:liberty.co.za', labels: ['bills', 'liberty'] },
  { id: 'sars-sender', query: 'from:sars.gov.za', labels: ['bills', 'sars'] },
  { id: 'fnb-sender', query: 'from:(fnbstatements.co.za OR fnb.co.za)', labels: ['finance', 'fnb'] },
  { id: 'absa-bank-sender', query: 'from:(absa.co.za OR absacapital.com)', labels: ['finance', 'absa'] },
  { id: 'stripe-sender', query: 'from:stripe.com', labels: ['finance', 'stripe'] },
  { id: 'wirex-sender', query: 'from:wirexapp.com', labels: ['finance', 'wirex'] },
  { id: 'wise-sender', query: 'from:wise.com', labels: ['finance', 'wise'] },
  { id: 'discovery-sender', query: 'from:discovery.co.za', labels: ['finance', 'discovery'] },
  { id: 'xm-sender', query: 'from:(xm.com OR xmglobal.com)', labels: ['finance', 'xm'] },
  { id: 'medium-sender', query: 'from:medium.com', labels: ['newsletters', 'medium'] },
  { id: 'seekingalpha-sender', query: 'from:seekingalpha.com', labels: ['newsletters', 'seekingalpha'] },
  { id: 'flippa-sender', query: 'from:flippa.com', labels: ['newsletters', 'flippa'] },
  { id: 'coursera-sender', query: 'from:coursera.org', labels: ['newsletters', 'coursera'] },
  { id: 'japanesepod101-sender', query: 'from:japanesepod101.com', labels: ['newsletters', 'japanesepod101'] },
  { id: 'mexc-newsletter-sender', query: 'from:(mexc.sg OR mexc.com)', labels: ['newsletters', 'mexc'] },
  { id: 'okx-sender', query: 'from:okx.com', labels: ['newsletters', 'okx'] },
  { id: 'gate-sender', query: 'from:(gate.io OR gate.com)', labels: ['newsletters', 'gate'] },
  { id: 'plus500-sender', query: 'from:plus500.com', labels: ['newsletters', 'plus500'] },
  { id: 'stackshare-sender', query: 'from:stackshare.io', labels: ['newsletters', 'stackshare'] },
  { id: 'tutorialsdojo-sender', query: 'from:tutorialsdojo.com', labels: ['newsletters', 'tutorialsdojo'] },
  { id: 'evernote-sender', query: 'from:evernote.com', labels: ['newsletters', 'evernote'] },
  { id: 'livescribe-sender', query: 'from:livescribe.com', labels: ['newsletters', 'livescribe'] },
  { id: 'quora-sender', query: 'from:quora.com', labels: ['newsletters', 'quora'] },
  { id: 'wordpress-sender', query: 'from:wordpress.com', labels: ['newsletters', 'wordpress'] },
  { id: 'meetup-sender', query: 'from:meetup.com', labels: ['newsletters', 'meetup'] },
  { id: 'offerzen-sender', query: 'from:offerzen.com', labels: ['newsletters', 'offerzen'] },
  { id: 'bitget-sender', query: 'from:bitget.com', labels: ['newsletters', 'bitget'] },
  { id: 'etoro-sender', query: 'from:etoro.com', labels: ['newsletters', 'etoro'] },
  { id: 'ideabrowser-sender', query: 'from:ideabrowser.com', labels: ['newsletters', 'ideabrowser'] },
  { id: 'justinwelsh-sender', query: 'from:justinwelsh.me', labels: ['newsletters', 'justinwelsh'] },
  { id: 'linuxacademy-sender', query: 'from:linuxacademy.com', labels: ['newsletters', 'linuxacademy'] },
  { id: 'lumosity-sender', query: 'from:lumosity.com', labels: ['newsletters', 'lumosity'] },
  { id: 'jobleads-sender', query: 'from:jobleads.com', labels: ['newsletters', 'jobleads'] },
  { id: 'maxmahershow-sender', query: 'from:maxmahershow.com', labels: ['newsletters', 'maxmahershow'] },
  { id: 'openai-sender', query: 'from:openai.com', labels: ['newsletters', 'openai'] },
  { id: 'scrimba-sender', query: 'from:scrimba.com', labels: ['newsletters', 'scrimba'] },
  { id: 'wallmine-sender', query: 'from:wallmine.com', labels: ['newsletters', 'wallmine'] },
  { id: 'pnet-sender', query: 'from:pnet.co.za', labels: ['newsletters', 'pnet'] },
  { id: 'tradingview-sender', query: 'from:tradingview.com', labels: ['newsletters', 'tradingview'] },
  { id: 'xt-sender', query: 'from:xt.com', labels: ['newsletters', 'xt'] },
  { id: 'kraken-sender', query: 'from:kraken.com', labels: ['newsletters', 'kraken'] },
  { id: 'ein-itin-sender', query: 'from:ein-itin.com', labels: ['newsletters', 'ein-itin'] },
  { id: 'juliangoldie-sender', query: 'from:juliangoldie.com', labels: ['newsletters', 'juliangoldie'] },
  { id: 'patreon-sender', query: 'from:patreon.com', labels: ['newsletters', 'patreon'] },
  { id: 'cal-sender', query: 'from:cal.com', labels: ['newsletters', 'cal'] },
  { id: 'discourse-sender', query: 'from:discoursemail.com', labels: ['newsletters', 'discourse'] },
  { id: 'replit-sender', query: 'from:replit.com', labels: ['newsletters', 'replit'] },
  { id: 'apple-sender', query: 'from:apple.com', labels: ['notifications', 'apple'] },
  { id: 'google-sender', query: 'from:google.com', labels: ['notifications', 'google'] },
  { id: 'bybit-sender', query: 'from:bybit.com', labels: ['notifications', 'bybit'] },
  { id: 'slack-sender', query: 'from:slack.com', labels: ['notifications', 'slack'] },
  { id: 'youtube-sender', query: 'from:youtube.com', labels: ['notifications', 'youtube'] },
  { id: 'binance-sender', query: 'from:binance.com', labels: ['notifications', 'binance'] },
  { id: 'coinex-sender', query: 'from:coinex.com', labels: ['notifications', 'coinex'] },
  { id: 'mexc-notification-sender', query: 'from:mexc.link', labels: ['notifications', 'mexc'] },
  { id: 'remote-sender', query: 'from:remote.com', labels: ['notifications', 'remote'] },
  { id: 'coinbase-sender', query: 'from:coinbase.com', labels: ['notifications', 'coinbase'] },
  { id: 'cex-sender', query: 'from:cex.io', labels: ['notifications', 'cex'] },
  { id: 'docusign-sender', query: 'from:docusign.net', labels: ['notifications', 'docusign'] },
  { id: 'payoneer-sender', query: 'from:payoneer.com', labels: ['notifications', 'payoneer'] },
  { id: 'luno-sender', query: 'from:luno.com', labels: ['notifications', 'luno'] },
  { id: 'gmail-personal-sender', query: 'from:gmail.com', labels: ['personal', 'gmail'] },
  { id: 'hotmail-personal-sender', query: 'from:hotmail.com', labels: ['personal', 'hotmail'] },
  { id: 'icloud-personal-sender', query: 'from:icloud.com', labels: ['personal', 'icloud'] },
  { id: 'yahoo-personal-sender', query: 'from:yahoo.com', labels: ['personal', 'yahoo'] },
  { id: 'acloud-sender', query: 'from:acloud.guru', labels: ['receipts', 'acloud'] },
  { id: 'jetbrains-sender', query: 'from:jetbrains.com', labels: ['receipts', 'jetbrains'] },
  { id: 'istore-sender', query: 'from:istore.co.za', labels: ['shopping', 'istore'] },
  { id: 'linkedin-sender', query: 'from:linkedin.com', labels: ['social', 'linkedin'] },
  { id: 'booking-sender', query: 'from:booking.com', labels: ['travel', 'booking'] },
  { id: 'vpm-sender', query: 'from:vpmteam.co.za', labels: ['work', 'vpm'] },
  { id: 'busyweb-sender', query: 'from:busyweb.co.za', labels: ['work', 'busyweb'] },
  { id: 'amazon-sender', query: 'from:amazon.com', labels: ['work', 'aws'] },
  { id: 'github-sender', query: 'from:github.com', labels: ['work', 'github'] },
  { id: 'notion-sender', query: 'from:notion.so', labels: ['work', 'notion'] },
  { id: 'pathosethos-sender', query: 'from:pathosethos.com', labels: ['work', 'pathosethos'] },
  { id: 'relevant-sender', query: 'from:relevant.us', labels: ['work', 'relevant'] },
  { id: 'surgenly-sender', query: 'from:surgenly.com', labels: ['work', 'surgenly'] },
  { id: 'trello-sender', query: 'from:trello.com', labels: ['work', 'trello'] },
  { id: 'verity-sender', query: 'from:veritybiosciences.com', labels: ['work', 'verity'] },
  { id: 'awsiq-sender', query: 'from:iq.aws', labels: ['work', 'awsiq'] },
  { id: 'datachef-sender', query: 'from:datachef.co', labels: ['work', 'datachef'] },
  { id: 'ioco-sender', query: 'from:ioco.tech', labels: ['work', 'ioco'] },
  { id: 'simola-sender', query: 'from:simola.co.za', labels: ['work', 'simola'] },
];

const SUBJECT_RULES = [
  { id: 'subject-receipts', query: 'subject:(receipt OR invoice OR "order confirmation" OR "your order" OR "thank you for your order" OR "thank you for your purchase")', labels: ['receipts'] },
  { id: 'subject-security-notifications', query: 'subject:("login from" OR "new sign-in" OR "new sign in" OR "your trade" OR "successful trade" OR "purchase for" OR "someone is accessing" OR "unusual sign-in" OR "security alert")', labels: ['notifications'] },
  { id: 'subject-otp', query: 'subject:("verification code" OR OTP OR "one-time password" OR "one time password" OR "your code" OR "login code" OR "security code" OR "authentication code" OR passcode OR two-factor OR "2fa code" OR "confirmation code" OR "access code" OR "sign-in code" OR "sign in code")', labels: ['otp'] },
];
